AWSTemplateFormatVersion: 2010-09-09
Description: SparkFlow stack configuration

Resources:

  ## DynamoDB tables ###################################################

  # Keeps a record of transforms onboarded to the SpakFlow system
  TransformsDDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      SSESpecification:
        SSEEnabled: 'false'
      AttributeDefinitions:
        - AttributeName: 'transform_id'
          AttributeType: 'S'
        - AttributeName: 'update_date'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'transform_id'
          KeyType: 'HASH'
        - AttributeName: 'update_date'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: "LastUpdateIndex"
          KeySchema:
            - AttributeName: "update_date"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: "sparkflow_transforms"

  # Keeps a record of individual job runs that have executed
  JobsDDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      SSESpecification:
        SSEEnabled: 'false'
      AttributeDefinitions:
        - AttributeName: 'job_id'
          AttributeType: 'S'
        - AttributeName: 'transform_id'
          AttributeType: 'S'
        - AttributeName: 'execute_date'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'job_id'
          KeyType: 'HASH'
        - AttributeName: 'execute_date'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: "ParentTransformIndex"
          KeySchema:
            - AttributeName: "transform_id"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: "sparkflow_job_runs"

  # Keeps a record of EMR cluster pools created by SparkFlow
  ClusterPoolDDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      SSESpecification:
        SSEEnabled: 'false'
      AttributeDefinitions:
        - AttributeName: 'cluster_pool_id'
          AttributeType: 'S'
        - AttributeName: 'update_date'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'cluster_pool_id'
          KeyType: 'HASH'
        - AttributeName: 'update_date'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: "LastUpdatedPoolIndex"
          KeySchema:
            - AttributeName: "update_date"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: "sparkflow_cluster_pools"

  # Keeps a record of individual clusters under the pools created by SparkFlow
  ClustersDDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      SSESpecification:
        SSEEnabled: 'false'
      AttributeDefinitions:
        - AttributeName: 'cluster_id'
          AttributeType: 'S'
        - AttributeName: 'update_date'
          AttributeType: 'S'
        - AttributeName: 'cluster_pool_id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'cluster_id'
          KeyType: 'HASH'
        - AttributeName: 'update_date'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: "ParentClusterPoolIndex"
          KeySchema:
            - AttributeName: "cluster_pool_id"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: "sparkflow_clusters"

  ## Queues #######################################################

  # Receives requests to create new EMR clusters
  ClusterCreationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "sparkflow-cluster-creation-dlq"
      VisibilityTimeout: 300

  ClusterCreationSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "sparkflow-cluster-creation-requests"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ClusterCreationDLQ.Arn
        maxReceiveCount: 10
      VisibilityTimeout: 300

  # Receives requests to create new EMR clusters
  ClusterDeletionDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "sparkflow-cluster-deletion-dlq"
      VisibilityTimeout: 300

  ClusterDeletionSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "sparkflow-cluster-deletion-requests"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ClusterDeletionDLQ.Arn
        maxReceiveCount: 10
      VisibilityTimeout: 300

  # Receives requests to create new transforms
  TransformCreationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "sparkflow-transform-creation-dlq"
      VisibilityTimeout: 300

  TransformCreationSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "sparkflow-transform-creation-requests"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TransformCreationDLQ.Arn
        maxReceiveCount: 10
      VisibilityTimeout: 300

  # Receives requests to delete transforms
  TransformDeletionDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "sparkflow-transform-deletion-dlq"
      VisibilityTimeout: 300

  TransformDeletionSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "sparkflow-transform-deletion-requests"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TransformDeletionDLQ.Arn
        maxReceiveCount: 10
      VisibilityTimeout: 300

  # Receives requests to create new job runs
  JobCreationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "sparkflow-job-creation-dlq"
      VisibilityTimeout: 300

  JobCreationSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "sparkflow-job-creation-requests"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt JobCreationDLQ.Arn
        maxReceiveCount: 10
      VisibilityTimeout: 300
